const $=id=>document.getElementById(id), results=$('results'), install=$('install');

function encode(value){const bytes=new TextEncoder().encode(JSON.stringify(value));let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary)}
function decode(value){const binary=atob(value),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function bookmarklet(){const target=location.origin+location.pathname;const targetLiteral=JSON.stringify(target);return `javascript:(function(){var l=window.__LEVEL__;if(!l){alert('Open an enclose.horse puzzle first.');return}var w=window.open('about:blank','_blank');var d=(window.__DAILY_LEVELS__||[]).filter(function(x){return String(x.dayNumber)===String(l.dayNumber)||x.id===l.id})[0]||{};var bid=l.bonusId||d.bonusId||(l.bonus&&l.bonus.id);var enc=function(o){var a=new TextEncoder().encode(JSON.stringify(o)),s='';for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s)};var done=function(b){var u=${targetLiteral}+'?level='+encodeURIComponent(enc(l))+(b?'&bonus='+encodeURIComponent(enc(b)):'');if(w&&!w.closed)w.location=u;else location.href=u};if(bid){fetch('/api/daily/bonus/'+encodeURIComponent(l.id)).then(function(r){if(!r.ok)throw Error('Bonus request failed ('+r.status+')');return r.json()}).then(function(b){b.type=l.bonusType||d.bonusType||(l.bonus&&l.bonus.type)||'default';b.name='Bonus round: '+String(b.type).toUpperCase();done(b)}).catch(function(e){if(w&&!w.closed)w.close();alert('Could not prepare this puzzle: '+e.message)})}else done(null)})()`}
$('bookmark').href=bookmarklet();

async function solve(puzzle){
  if(!window.TeaVM?.wasmGC)throw Error('solver.wasm-runtime.js is missing. Run the WASM build first.');
  const vm=await TeaVM.wasmGC.load('solver.wasm');
  const optimal=puzzle.optimalScore==null?-2147483648:Number(puzzle.optimalScore);
  const raw=vm.exports.solve(puzzle.map,puzzle.budget,puzzle.type||'default',optimal,12);
  return typeof raw==='string'?JSON.parse(raw):JSON.parse(String(raw));
}
function paint(puzzle,solution,card){const rows=puzzle.map.replace(/\r/g,'').split('\n'),h=rows.length,w=rows[0].length,board=card.querySelector('.board'),walls=new Set(solution.walls);[...board.children].forEach((cell,i)=>{cell.classList.toggle('wall',walls.has(i));cell.classList.toggle('solution',walls.has(i));});card.querySelector('strong').textContent=solution.score;card.querySelector('small').textContent=`${solution.walls.length} walls used`}
function working(status,message){status.querySelector('small').innerHTML=`<span class="working"><span class="spinner"></span>${message}</span>`;status.querySelectorAll('button').forEach(button=>button.disabled=true)}
function nextFrame(){return new Promise(resolve=>requestAnimationFrame(resolve))}
function card(puzzle){const rows=puzzle.map.replace(/\r/g,'').split('\n'),h=rows.length,w=rows[0].length,card=document.createElement('article');card.className='level '+(puzzle.type&&puzzle.type!=='default'?'bonus':'');if(puzzle.type&&puzzle.type!=='default')card.style.setProperty('--bonus-bg',puzzle.type==='lovebirds'?'#182b2b':puzzle.type==='loversquarrel'?'#2d2025':'#302719');card.innerHTML=`<h2>${puzzle.name||'Enclose.horse level'}</h2><div class="meta">Puzzle ${puzzle.id||''} · wall budget ${puzzle.budget}</div>`;const board=document.createElement('div');board.className='board';board.style.gridTemplateColumns=`repeat(${w},var(--cell))`;rows.forEach(row=>[...row].forEach(c=>{const e=document.createElement('div');e.className='cell';e.textContent={H:'🐴',U:'🦄',C:'🍒',G:'🍎',S:'🐝'}[c]||'';board.append(e)}));const wrap=document.createElement('div');wrap.className='board-wrap';wrap.append(board);card.append(wrap);const status=document.createElement('div');status.className='status';status.innerHTML='<div class="score">Optimal score <strong>…</strong><small>solving in Java WASM…</small></div><div class="controls"><button disabled>← Previous</button><button disabled>Next →</button></div>';card.append(status);return {card,board,status}}
async function start(){const params=new URLSearchParams(location.search),encoded=params.get('level');if(!encoded)return;install.hidden=true;const puzzles=[decode(encoded)];if(params.get('bonus'))puzzles.push(decode(params.get('bonus')));results.hidden=false;for(const puzzle of puzzles){const view=card(puzzle),cardElement=view.card,status=view.status;results.append(cardElement);try{working(status,'finding the first optimal solution…');await nextFrame();const output=await solve(puzzle),solutions=output.solutions||[];if(!solutions.length)throw Error('No legal solution found');let at=0;const show=()=>{paint(puzzle,solutions[at],cardElement);status.querySelector('small').textContent=`solution ${at+1} / ${solutions.length}`;const buttons=status.querySelectorAll('button');buttons[0].disabled=at===0;buttons[1].disabled=at===solutions.length-1;buttons[0].onclick=async()=>{working(status,'finding previous optimal solution…');await nextFrame();at--;show()};buttons[1].onclick=async()=>{working(status,'finding next optimal solution…');await nextFrame();at++;show()}};show()}catch(e){status.querySelector('small').textContent=e.message;console.error(e)}}}
start().catch(e=>{results.hidden=false;results.innerHTML=`<div class="error">${e.message}</div>`});
