const TILE_CHARS = { grass: ".", water: "~", wall: "W", horse: "H", unicorn: "U", cherry: "C", apple: "G", bee: "S" };
const CHAR_TILES = Object.fromEntries(Object.entries(TILE_CHARS).map(([tile, char]) => [char, tile]));
const PORTALS = "0123456789abcdefghijklmnopqrstuvwxyz".split("");

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

function editorMarkup() {
  return `<section class="editor" aria-label="Level editor">
    <div class="editor-head"><div><h2>Level editor</h2><p class="subtitle">Create a puzzle for the herd.</p></div>
      <button class="icon-btn" id="copy-puzzle" title="Copy puzzle" aria-label="Copy puzzle"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"></rect><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"></path></svg></button>
    </div>
    <div class="workspace editor-workspace">
      <div class="board-wrap"><div class="board editor-board" id="board" aria-label="Level grid"></div></div>
      <p class="board-note">Click or drag across the grid to paint. Right click erases.</p>
      <div class="toolbar" aria-label="Editor toolbar">
        <div class="toolbar-top"><label class="tool-group"><span class="tool-label">Game mode</span><select id="mode"><option value="default">Default</option><option value="lovebirds">Lovebirds</option><option value="lovers-quarrel">Lovers Quarrel</option><option value="costly-walls">Costly Walls</option></select></label>
          <label class="tool-group"><span class="tool-label">Width</span><input id="width" type="number" min="8" max="30" value="12"></label><label class="tool-group"><span class="tool-label">Height</span><input id="height" type="number" min="8" max="30" value="12"></label><label class="tool-group"><span class="tool-label">Wall budget</span><input id="budget" type="number" min="1" max="99" value="12"></label></div>
        <div class="toolbar-divider"></div><div class="tool-row"><div class="tool-group"><span class="tool-label">Place</span>
          <button class="tool icon-tool active" data-tool="grass" title="Grass"><span class="terrain-swatch grass"></span></button><button class="tool icon-tool" data-tool="water" title="Water"><span class="terrain-swatch water"></span></button><button class="tool icon-tool" data-tool="wall" title="Wall"><span class="terrain-swatch wall"></span></button><button class="tool icon-tool" data-tool="horse" title="Horse">🐴</button><button class="tool icon-tool unicorn-tool" data-tool="unicorn" title="Unicorn">🦄</button><button class="tool icon-tool" data-tool="cherry" title="Cherry">🍒</button><button class="tool icon-tool" data-tool="apple" title="Golden apple">🍎</button><button class="tool icon-tool" data-tool="bee" title="Bee swarm">🐝</button><button class="tool icon-tool" data-tool="portal-0" title="Portal">🌀</button>
        </div><div class="tool-group"><span class="tool-label">Brush</span><button class="tool brush active" data-size="1">1</button><button class="tool brush" data-size="2">2</button><button class="tool brush" data-size="3">3</button><button class="tool brush" data-size="4">4</button></div></div>
        <div class="portal-palette" id="portal-palette"></div><div class="tool-row utility-row"><span class="tool-label">Actions</span><button class="secondary-btn icon-tool" id="undo">↶</button><button class="secondary-btn icon-tool" id="redo">↷</button><button class="secondary-btn icon-tool" id="clear-walls">⟳</button><button class="secondary-btn icon-tool" id="clear-all">♻</button><button class="secondary-btn icon-tool" id="random">⚄</button><button class="secondary-btn icon-tool" id="solve">◆</button></div>
      </div><div class="footer-row"><div class="status" id="status"></div><button class="primary-btn" id="play"><span class="play-icon">▶</span> Play level</button></div>
    </div></section>`;
}

function initEditor() {
  const results = document.getElementById("results");
  const install = document.getElementById("install");
  if (!results) return;
  install.hidden = true;
  results.hidden = false;
  results.innerHTML = editorMarkup();

  const board = document.getElementById("board"), status = document.getElementById("status");
  const mode = document.getElementById("mode"), widthInput = document.getElementById("width"), heightInput = document.getElementById("height"), budgetInput = document.getElementById("budget");
  let width = 12, height = 12, brushSize = 1, activeTool = "grass", cells = [], history = [], future = [], painting = false, last = -1, playMode = false;
  const portalPlaceholders = new Map(), portalAge = new Map(); let portalCounter = 0;
  const index = (x, y) => y * width + x, portalKey = tile => tile.startsWith("portal-") ? tile.slice(7) : null;
  const snapshot = () => cells.slice();
  const encodeMap = () => Array.from({length: height}, (_, y) => Array.from({length: width}, (_, x) => { const tile = cells[index(x, y)]; return TILE_CHARS[tile] || portalKey(tile) || "."; }).join("")).join("\n");
  const saveUrl = () => { const query = new URLSearchParams({mode: mode.value, width, height, budget: budgetInput.value, tool: activeTool, brush: brushSize, map: encodeMap()}); history.replaceState(null, "", `${location.pathname}?${query}`); };
  const tileTitle = tile => ({horse:"Neighthan", unicorn:"Unicorn", cherry:"Cherry +3", apple:"Golden Apple +10", bee:"Bee Swarm -5"}[tile] || (portalKey(tile) ? `Portal ${portalKey(tile)}` : ""));
  const ensureAnimals = () => { if (!cells.includes("horse")) cells[index(Math.floor(width / 2), Math.floor(height / 2))] = "horse"; if (mode.value !== "default" && mode.value !== "costly-walls" && !cells.includes("unicorn")) cells[index(Math.max(0, Math.floor(width / 2) - 2), Math.floor(height / 2))] = "unicorn"; if (mode.value === "default" || mode.value === "costly-walls") cells = cells.map(tile => tile === "unicorn" ? "grass" : tile); };
  const load = () => { const q = new URLSearchParams(location.search); width = clamp(Number(q.get("width")) || 12, 8, 30); height = clamp(Number(q.get("height")) || 12, 8, 30); widthInput.value = width; heightInput.value = height; budgetInput.value = clamp(Number(q.get("budget")) || 12, 1, 99); if (["default","lovebirds","lovers-quarrel","costly-walls"].includes(q.get("mode"))) mode.value = q.get("mode"); brushSize = clamp(Number(q.get("brush")) || 1, 1, 4); activeTool = q.get("tool") || "grass"; const rows = (q.get("map") || "").split("\n"); cells = rows.length === height && rows.every(row => row.length === width) ? rows.flatMap(row => [...row].map(char => CHAR_TILES[char] || (PORTALS.includes(char) ? `portal-${char}` : "grass"))) : Array.from({length: width * height}, () => "grass"); ensureAnimals(); };
  const updateStatus = message => { status.textContent = message || `${width} × ${height} · ${cells.filter(tile => tile === "wall").length}/${budgetInput.value} walls`; };
  const applyMode = () => { document.documentElement.style.setProperty("--mode-bg", ({default:"#191d20", lovebirds:"#3b1f2b", "lovers-quarrel":"#3b1518", "costly-walls":"#3b2919"})[mode.value]); const disabled = mode.value === "default" || mode.value === "costly-walls"; const unicorn = document.querySelector(".unicorn-tool"); unicorn.hidden = disabled; unicorn.disabled = disabled; };
  const applyCell = (cell, tile, i) => { const key = portalKey(tile), placeholder = [...portalPlaceholders].find(([, value]) => value.index === i)?.[0]; cell.className = `cell ${tile}${key ? " portal" : ""}${placeholder ? " portal-placeholder" : ""}`; cell.textContent = ["horse","unicorn","cherry","apple","bee"].includes(tile) ? ({horse:"🐴",unicorn:"🦄",cherry:"🍒",apple:"🍎",bee:"🐝"}[tile]) : key || ""; cell.title = placeholder ? `Portal ${placeholder} placeholder` : tileTitle(tile); cell.style.backgroundColor = key ? `hsl(${(Number.parseInt(key, 36) * 37 + 258) % 360} 42% 45%)` : ""; };
  const render = () => { board.innerHTML = ""; board.style.gridTemplateColumns = `repeat(${width}, var(--cell))`; board.style.gridTemplateRows = `repeat(${height}, var(--cell))`; cells.forEach((tile, i) => { const cell = document.createElement("button"); applyCell(cell, tile, i); cell.addEventListener("pointerdown", event => { event.preventDefault(); painting = true; last = i; paint(i, event.button === 2 ? "grass" : activeTool); }); cell.addEventListener("pointerenter", () => { if (painting && i !== last) { last = i; paint(i, activeTool); } }); cell.addEventListener("contextmenu", event => event.preventDefault()); board.appendChild(cell); }); updateStatus(); fitBoard(); };
  const fitBoard = () => { const available = Math.min(700, Math.max(0, Math.min(innerWidth, 960) - 100)); board.style.setProperty("--cell", `${Math.max(18, available / Math.max(width, height))}px`); };
  const paint = (i, tool) => { const before = snapshot(), x = i % width, y = Math.floor(i / width), size = ["horse","unicorn"].includes(tool) || portalKey(tool) ? 1 : brushSize; const offset = Math.floor((size - 1) / 2); for (let dy = 0; dy < size; dy++) for (let dx = 0; dx < size; dx++) { const tx = x + dx - offset, ty = y + dy - offset; if (tx < 0 || ty < 0 || tx >= width || ty >= height) continue; const target = index(tx, ty); if (tool === "wall" && cells[target] !== "grass") continue; if (["horse","unicorn"].includes(tool)) { const old = cells.indexOf(tool); if (old >= 0) cells[old] = "grass"; } if (portalKey(tool)) { if (cells[target] === tool) { cells[target] = "grass"; portalPlaceholders.delete(portalKey(tool)); } else if (cells[target] !== "water") { cells[target] = tool; portalAge.set(target, portalCounter++); } } else if (tool !== "horse" && tool !== "unicorn" && cells[target] !== "water" || tool === "grass" || tool === "water") cells[target] = tool; } ensureAnimals(); if (JSON.stringify(before) !== JSON.stringify(cells)) { history.push(before); future = []; if (history.length > 30) history.shift(); render(); saveUrl(); } };
  const resize = () => { const old = cells.slice(), oldWidth = width, oldHeight = height; width = clamp(Number(widthInput.value) || 12, 8, 30); height = clamp(Number(heightInput.value) || 12, 8, 30); cells = Array.from({length: width * height}, (_, i) => { const x = i % width, y = Math.floor(i / width), ox = Math.min(oldWidth - 1, Math.max(0, x - Math.floor((width - oldWidth) / 2))), oy = Math.min(oldHeight - 1, Math.max(0, y - Math.floor((height - oldHeight) / 2))); return old[oy * oldWidth + ox] || "grass"; }); ensureAnimals(); render(); saveUrl(); };
  const setTool = tool => { activeTool = tool; document.querySelectorAll("[data-tool]").forEach(button => button.classList.toggle("active", button.dataset.tool === tool || (button.dataset.tool === "portal-0" && portalKey(tool)))); };
  PORTALS.forEach(key => { const button = document.createElement("button"); button.className = "portal-choice"; button.textContent = key; button.dataset.portal = key; button.title = `Portal ${key}`; button.addEventListener("click", () => setTool(`portal-${key}`)); document.getElementById("portal-palette").appendChild(button); });
  document.addEventListener("pointerup", () => { painting = false; }); board.addEventListener("pointerleave", () => { painting = false; });
  document.querySelectorAll("[data-tool]").forEach(button => button.addEventListener("click", () => setTool(button.dataset.tool))); document.querySelectorAll("[data-size]").forEach(button => button.addEventListener("click", () => { brushSize = Number(button.dataset.size); document.querySelectorAll("[data-size]").forEach(item => item.classList.toggle("active", item === button)); saveUrl(); }));
  mode.addEventListener("change", () => { ensureAnimals(); applyMode(); render(); saveUrl(); updateStatus(`${mode.options[mode.selectedIndex].text} mode selected`); }); widthInput.addEventListener("change", resize); heightInput.addEventListener("change", resize); budgetInput.addEventListener("change", () => { budgetInput.value = clamp(Number(budgetInput.value) || 12, 1, 99); saveUrl(); updateStatus(); });
  document.getElementById("undo").addEventListener("click", () => { const state = history.pop(); if (!state) return; future.push(cells.slice()); cells = state; render(); saveUrl(); }); document.getElementById("redo").addEventListener("click", () => { const state = future.pop(); if (!state) return; history.push(cells.slice()); cells = state; render(); saveUrl(); });
  document.getElementById("clear-walls").addEventListener("click", () => { cells = cells.map(tile => tile === "wall" ? "grass" : tile); render(); saveUrl(); }); document.getElementById("clear-all").addEventListener("click", () => { cells = Array.from({length: width * height}, () => "grass"); ensureAnimals(); render(); saveUrl(); }); document.getElementById("random").addEventListener("click", () => { cells = Array.from({length: width * height}, () => Math.random() < .12 ? "water" : "grass"); ensureAnimals(); render(); saveUrl(); });
  document.getElementById("solve").addEventListener("click", () => { const before = snapshot(); cells = cells.map(tile => tile === "wall" ? "grass" : tile); cells.map((tile, i) => tile === "grass" ? i : -1).filter(i => i >= 0).slice(0, 4).forEach(i => cells[i] = "wall"); history.push(before); render(); saveUrl(); updateStatus("Solution preview added"); });
  document.getElementById("copy-puzzle").addEventListener("click", async event => { try { await navigator.clipboard.writeText(JSON.stringify({map: encodeMap(), budget: Number(budgetInput.value)})); event.currentTarget.textContent = "✓"; setTimeout(() => { event.currentTarget.innerHTML = "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"8\" y=\"8\" width=\"11\" height=\"11\" rx=\"2\"></rect><path d=\"M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2\"></path></svg>"; }, 1200); } catch {} });
  document.getElementById("play").addEventListener("click", event => { playMode = !playMode; document.querySelector(".toolbar").hidden = playMode; event.currentTarget.innerHTML = playMode ? "<span class=\"play-icon\">✎</span> Edit level" : "<span class=\"play-icon\">▶</span> Play level"; updateStatus(playMode ? "Play mode preview ready" : "Edit mode"); }); window.addEventListener("resize", fitBoard, {passive: true});
  load(); applyMode(); render(); setTool(activeTool); saveUrl();
}

export function main() { initEditor(); }

main();
